storage:
    resource: "@StorageBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /api
app:
    resource: '@AppBundle/Controller/'
    type: rest
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"